#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("roots.Resource", IsApplication=true)]

namespace roots
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int Button_Dismiss = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int MyButton = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int add_driver_name_label = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int add_new_drivers_button = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int add_new_drivers_name = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int edit_toolbar = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int menu_add_driver = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int menu_driver_details = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int menu_driver_image = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int menu_edit = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int menu_preferences2 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int menu_preferences3 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int menu_preferences4 = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int menu_save = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int sampleTextView = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int toolbar = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Add_new_driver = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int settingsTab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int tab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int toolbar = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int driver_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int top_menu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_a_photo_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_details_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_directions_car_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_copy_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_cut_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_paste_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_search_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_pie_chart_white_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_plus_one_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon = 2130837515;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int add_driver_button = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int add_driver_details_button = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int add_driver_form_name_label = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int add_driver_image_button = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int history_tab = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int review_driver_details_button = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int settings_tab = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int statistics_tab = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int trip_tab = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
