#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("roots.Resource", IsApplication=true)]

namespace roots
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microcharts.Droid.Resource.String.library_name = global::roots.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_up = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070002
			public const int colorAccent = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int colorPrimary = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int colorPrimaryDark = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundimage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int xs = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000d
			public const int AddTripButton = 2131361805;
			
			// aapt resource value: 0x7f0a0009
			public const int DescriptionLabel = 2131361801;
			
			// aapt resource value: 0x7f0a002a
			public const int DriversListView = 2131361834;
			
			// aapt resource value: 0x7f0a002c
			public const int JourneyListView = 2131361836;
			
			// aapt resource value: 0x7f0a0028
			public const int MyButton = 2131361832;
			
			// aapt resource value: 0x7f0a0007
			public const int NameLabel = 2131361799;
			
			// aapt resource value: 0x7f0a002e
			public const int TripListView = 2131361838;
			
			// aapt resource value: 0x7f0a000b
			public const int WhenLabel = 2131361803;
			
			// aapt resource value: 0x7f0a0000
			public const int add_driver_name_label = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int add_new_drivers_button = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int add_new_drivers_name = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int add_stopPlace_label = 2131361795;
			
			// aapt resource value: 0x7f0a0005
			public const int add_stopplace_button = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int add_stopplace_text = 2131361796;
			
			// aapt resource value: 0x7f0a0015
			public const int btnMainJourneyButton = 2131361813;
			
			// aapt resource value: 0x7f0a0013
			public const int btnStar = 2131361811;
			
			// aapt resource value: 0x7f0a0038
			public const int buttonFunFacts = 2131361848;
			
			// aapt resource value: 0x7f0a0036
			public const int buttonMakeTripActive = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int buttonViewJourneys = 2131361847;
			
			// aapt resource value: 0x7f0a0020
			public const int dattimeHeaderRow = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int dayHeader = 2131361822;
			
			// aapt resource value: 0x7f0a0023
			public const int daytimeDetailsRow = 2131361827;
			
			// aapt resource value: 0x7f0a002b
			public const int driverMenu = 2131361835;
			
			// aapt resource value: 0x7f0a0014
			public const int driverSelectSpinner = 2131361812;
			
			// aapt resource value: 0x7f0a000e
			public const int driver_spinner_image = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int driver_spinner_name = 2131361807;
			
			// aapt resource value: 0x7f0a000a
			public const int editTripDescription = 2131361802;
			
			// aapt resource value: 0x7f0a0008
			public const int editTripName = 2131361800;
			
			// aapt resource value: 0x7f0a000c
			public const int editTripWhen = 2131361804;
			
			// aapt resource value: 0x7f0a0011
			public const int imgDriverScreenDriverAvater = 2131361809;
			
			// aapt resource value: 0x7f0a002d
			public const int journeyMenu = 2131361837;
			
			// aapt resource value: 0x7f0a001f
			public const int lblDailyLabel = 2131361823;
			
			// aapt resource value: 0x7f0a0024
			public const int lblDayDistanceData = 2131361828;
			
			// aapt resource value: 0x7f0a0021
			public const int lblDayDistanceLabel = 2131361825;
			
			// aapt resource value: 0x7f0a0025
			public const int lblDayTimeData = 2131361829;
			
			// aapt resource value: 0x7f0a0022
			public const int lblDayTimeLabel = 2131361826;
			
			// aapt resource value: 0x7f0a001c
			public const int lblDistanceData = 2131361820;
			
			// aapt resource value: 0x7f0a0019
			public const int lblDistanceLabel = 2131361817;
			
			// aapt resource value: 0x7f0a001d
			public const int lblTimeData = 2131361821;
			
			// aapt resource value: 0x7f0a001a
			public const int lblTimeLabel = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int lblTripLabel = 2131361815;
			
			// aapt resource value: 0x7f0a003c
			public const int menu_add_driver = 2131361852;
			
			// aapt resource value: 0x7f0a0043
			public const int menu_add_trip = 2131361859;
			
			// aapt resource value: 0x7f0a003b
			public const int menu_driver_details = 2131361851;
			
			// aapt resource value: 0x7f0a003d
			public const int menu_edit = 2131361853;
			
			// aapt resource value: 0x7f0a003f
			public const int menu_preferences2 = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int menu_preferences3 = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int menu_preferences4 = 2131361857;
			
			// aapt resource value: 0x7f0a003e
			public const int menu_save = 2131361854;
			
			// aapt resource value: 0x7f0a0042
			public const int menu_trip_details = 2131361858;
			
			// aapt resource value: 0x7f0a0029
			public const int spinner = 2131361833;
			
			// aapt resource value: 0x7f0a001b
			public const int timeDetailsRow = 2131361819;
			
			// aapt resource value: 0x7f0a0018
			public const int timeHeaderRow = 2131361816;
			
			// aapt resource value: 0x7f0a0006
			public const int toolbar = 2131361798;
			
			// aapt resource value: 0x7f0a0031
			public const int tripDetailsMilesTraveledDetails = 2131361841;
			
			// aapt resource value: 0x7f0a0030
			public const int tripDetailsMilesTraveledHeader = 2131361840;
			
			// aapt resource value: 0x7f0a0033
			public const int tripDetailsTimesTraveledDetails = 2131361843;
			
			// aapt resource value: 0x7f0a0032
			public const int tripDetailsTimesTraveledHeader = 2131361842;
			
			// aapt resource value: 0x7f0a0035
			public const int tripDetailsTripsTraveledDetails = 2131361845;
			
			// aapt resource value: 0x7f0a0034
			public const int tripDetailsTripsTraveledHeader = 2131361844;
			
			// aapt resource value: 0x7f0a0016
			public const int tripHeader = 2131361814;
			
			// aapt resource value: 0x7f0a002f
			public const int tripMenu = 2131361839;
			
			// aapt resource value: 0x7f0a0012
			public const int txtDriverScreenDriverName = 2131361810;
			
			// aapt resource value: 0x7f0a0027
			public const int txtJourneyDriver = 2131361831;
			
			// aapt resource value: 0x7f0a0010
			public const int txtJourneyScreenDriverName = 2131361808;
			
			// aapt resource value: 0x7f0a0026
			public const int txtJourneyTimes = 2131361830;
			
			// aapt resource value: 0x7f0a0039
			public const int txtTripScreenTripName = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int txtTripScreenTripWhen = 2131361850;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Add_new_driver = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Add_New_Stopping_Point = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AddTripScreen = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Driver_Spinner_Row = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int DriverJourneyListViewRow = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int DriverListViewRow = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int JourneyLayout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int JourneyListVewRowLayout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Main = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int MainDriverScreen = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int MainJourneyListScreen = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int MainMenuBackground = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int MainTripScreen = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int TripDetails = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int TripListViewRow = 2130968590;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int driver_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MainMenuItems = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int trip_menu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_create = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_content_save = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_add_a_photo_white_24dp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_details_white_24dp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_directions_car_white_24dp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_menu_copy_holo_dark = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ic_menu_cut_holo_dark = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ic_menu_paste_holo_dark = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ic_menu_search_holo_dark = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ic_pie_chart_white_24dp = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ic_plus_one_white_24dp = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int icon = 2130903051;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000a
			public const int add_driver_button = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int add_driver_details_button = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int add_driver_form_name_label = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int add_driver_image_button = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int add_stopplace_button_label = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int add_stopplace_label_string = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int history_tab = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int review_driver_details_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int settings_tab = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int statistics_tab = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int trip_tab = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int AppTheme = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int MyTheme = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int dialog_animation = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
